### ISSUE TITLE
Strange Issue on beginning a run with this patch enabled.

### ISSUE THREAD

**Issue by Dignut** [RicoValdezio/RoR2-GeneticVariantsPatch#2]
When starting a run with this patch enabled and the artifact turned on, the drop pod never comes down on run start and the camera is weird and zoomed outwards, very.. odd, the dev log ingame doesn't give any particular pointers to anything either.

**Comment by Dignut** [comment]
here's the bepinex log, if it'll help give any insight, 
[LogOutPut.log](https://github.com/user-attachments/files/17619775/LogOutPut.log)

**Comment by RicoValdezio** [comment]
It looks like Nebby changed the naming convention for the VariantCatalog I was trying to load from. I'll try and get a fix for this out sometime today.

**Comment by RicoValdezio** [comment]
Got a temporary fix deployed with v0.4.0. Should take care of that nullref you're getting on run start.
